/*
 * This source file was generated by the Gradle 'init' task
 */
package escenario;

import java.util.Scanner;

public class App {
    // El ratio cambiaro se de actualizar diariamente, para efectos prácticos del ejercicio asumimos un valor constante
    public final static double RATIO_EUROPA = 4253.40;
    public final static double DESCUENTO_MEDIO_DIA = 0.1;

    public static int siglo(int anho) {
        return (anho - 1) / 100 + 1;
    }

    public static int primer_anho(int siglo) {
        return (siglo - 1) * 100 + 1;
    }

    public static double conversionALas8AM(double monedaLocalP) {
        return monedaLocalP / RATIO_EUROPA;
    }

    public static double conversionAlMedioDia(double monedaLocalP) {
        double ratioConDescuento = RATIO_EUROPA - (RATIO_EUROPA * DESCUENTO_MEDIO_DIA);
        return monedaLocalP / ratioConDescuento;
    }

    public static double metrosAPies(double metros) {
        return metros * 3.28084;
    }

    public static double metrosAPulgadas(double metros) {
        return metros * 39.3701;
    }

    public static double metrosACentimetros(double metros) {
        return metros * 100;
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        boolean salir = false;

        while (!salir) {
            System.out.println("\n=== MENU ===");
            System.out.println("1. Consultar año en siglos");
            System.out.println("2. Convertir moneda");
            System.out.println("3. Conversión de medidas de longitud");
            System.out.println("4. Salir");
            System.out.print("Elija una opción (1, 2, 3 o 4): ");
            int opcion = scanner.nextInt();

            switch (opcion) {
                case 1:
                    System.out.print("Ingrese un año: ");
                    int anho = scanner.nextInt();
                    int siglo = siglo(anho);
                    int primerAnho = primer_anho(siglo);
                    System.out.println("El año " + anho + " pertenece al siglo " + siglo);
                    System.out.println("El primer año de ese siglo es: " + primerAnho);
                    break;
                case 2:
                    System.out.print("Ingrese la cantidad en moneda local (en pesos): ");
                    double monedaLocal = scanner.nextDouble();
                    double euros = conversionALas8AM(monedaLocal);
                    System.out.println("Equivalente en euros a las 8:00 AM: " + String.format("%.2f €", euros));
                    double eurosMedioDia = conversionAlMedioDia(monedaLocal);
                    System.out.println("Equivalente en euros a las 12:00 PM: " + String.format("%.2f €", eurosMedioDia));
                    break;
                case 3:
                    System.out.print("Ingrese el número de metros: ");
                    double metros = scanner.nextDouble();
                    System.out.println(metros + " metros equivalen a:");
                    System.out.println("  - " + String.format("%.2f", metrosAPies(metros)) + " pies");
                    System.out.println("  - " + String.format("%.2f", metrosAPulgadas(metros)) + " pulgadas");
                    System.out.println("  - " + String.format("%.2f", metrosACentimetros(metros)) + " centímetros");
                    break;
                case 4:
                    salir = true;
                    System.out.println("Hasta luego.");
                    break;
                default:
                    System.out.println("Opción no válida. Intente de nuevo.");
            }
        }

        scanner.close();
    }
}
