/*
 * This source file was generated by the Gradle 'init' task
 */
package escenario;

import java.util.Scanner;

public class App {
    public static int siglo(int anho) {
        return (anho - 1) / 100 + 1;
    }

    public static int primer_anho(int siglo) {
        return (siglo - 1) * 100 + 1;
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        System.out.print("Ingrese un año: ");
        int anho = scanner.nextInt();

        int siglo = siglo(anho);
        int primerAnho = primer_anho(siglo);

        System.out.println("El año " + anho + " pertenece al siglo " + siglo);
        System.out.println("El primer año de ese siglo es: " + primerAnho);

        scanner.close();
    }
}
