/*
 * This source file was generated by the Gradle 'init' task
 */
package escenario;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void sigloTest() {
        assertEquals(1, App.siglo(100));
        assertEquals(2, App.siglo(120));
    }

    @Test void primerAnhoTest() {
        assertEquals(1, App.primer_anho(1));
        assertEquals(101, App.primer_anho(2));
    }
}
